=== avto-dev/static-references-data/data/subject/codes.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "minLength": 1,
    "items": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "minLength": 1
            },
            "code": {
                "type": "integer",
                "minimum": 1,
                "maximum": 99
            },
            "gibdd": {
                "type": "array",
                "minLength": 1,
                "items": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 999
                }
            },
            "code_iso_31662": {
                "type": "string",
                "minLength": 1,
                "pattern": "[A-Z]{2}-[A-Z]{2,3}"
            }
        },
        "additionalProperties": false
    }
}

=== avto-dev/static-references-data/data/subject/codes.json
[
    {
        "title": "Республика Адыгея",
        "code": 1,
        "gibdd": [
            1
        ],
        "code_iso_31662": "RU-AD"
    },
    {
        "title": "Республика Башкортостан",
        "code": 2,
        "gibdd": [
            2,
            102,
            702
        ],
        "code_iso_31662": "RU-BA"
    },
    {
        "title": "Республика Бурятия",
        "code": 3,
        "gibdd": [
            3,
            103
        ],
        "code_iso_31662": "RU-BU"
    },
    {
        "title": "Республика Алтай",
        "code": 4,
        "gibdd": [
            4
        ],
        "code_iso_31662": "RU-AL"
    },
    {
        "title": "Республика Дагестан",
        "code": 5,
        "gibdd": [
            5,
            105
        ],
        "code_iso_31662": "RU-DA"
    },
    {
        "title": "Республика Ингушетия",
        "code": 6,
        "gibdd": [
            6
        ],
        "code_iso_31662": "RU-IN"
    },
    {
        "title": "Кабардино-Балкарская республика",
        "code": 7,
        "gibdd": [
            7
        ],
        "code_iso_31662": "RU-KB"
    },
    {
        "title": "Республика Калмыкия",
        "code": 8,
        "gibdd": [
            8
        ],
        "code_iso_31662": "RU-KL"
    },
    {
        "title": "Карачаево-Черкесская республика",
        "code": 9,
        "gibdd": [
            9
        ],
        "code_iso_31662": "RU-KC"
    },
    {
        "title": "Республика Карелия",
        "code": 10,
        "gibdd": [
            10
        ],
        "code_iso_31662": "RU-KR"
    },
    {
        "title": "Республика Коми",
        "code": 11,
        "gibdd": [
            11,
            111
        ],
        "code_iso_31662": "RU-KO"
    },
    {
        "title": "Республика Марий Эл",
        "code": 12,
        "gibdd": [
            12,
            112
        ],
        "code_iso_31662": "RU-ME"
    },
    {
        "title": "Республика Мордовия",
        "code": 13,
        "gibdd": [
            13,
            113
        ],
        "code_iso_31662": "RU-MO"
    },
    {
        "title": "Республика Саха (Якутия)",
        "code": 14,
        "gibdd": [
            14
        ],
        "code_iso_31662": "RU-SA"
    },
    {
        "title": "Республика Северная Осетия - Алания",
        "code": 15,
        "gibdd": [
            15
        ],
        "code_iso_31662": "RU-SE"
    },
    {
        "title": "Республика Татарстан",
        "code": 16,
        "gibdd": [
            16,
            116,
            716
        ],
        "code_iso_31662": "RU-TA"
    },
    {
        "title": "Республика Тыва",
        "code": 17,
        "gibdd": [
            17
        ],
        "code_iso_31662": "RU-TY"
    },
    {
        "title": "Удмуртская республика",
        "code": 18,
        "gibdd": [
            18,
            118
        ],
        "code_iso_31662": "RU-UD"
    },
    {
        "title": "Республика Хакасия",
        "code": 19,
        "gibdd": [
            19
        ],
        "code_iso_31662": "RU-KK"
    },
    {
        "title": "Чеченская республика",
        "code": 20,
        "gibdd": [
            95
        ],
        "code_iso_31662": "RU-CE"
    },
    {
        "title": "Чувашская республика",
        "code": 21,
        "gibdd": [
            21,
            121
        ],
        "code_iso_31662": "RU-CU"
    },
    {
        "title": "Алтайский край",
        "code": 22,
        "gibdd": [
            22,
            122
        ],
        "code_iso_31662": "RU-ALT"
    },
    {
        "title": "Краснодарский край",
        "code": 23,
        "gibdd": [
            23,
            93,
            123,
            193,
            323
        ],
        "code_iso_31662": "RU-KDA"
    },
    {
        "title": "Красноярский край",
        "code": 24,
        "gibdd": [
            24,
            124,
            224,
            88
        ],
        "code_iso_31662": "RU-KYA"
    },
    {
        "title": "Приморский край",
        "code": 25,
        "gibdd": [
            25,
            125,
            725
        ],
        "code_iso_31662": "RU-PRI"
    },
    {
        "title": "Ставропольский край",
        "code": 26,
        "gibdd": [
            26,
            126
        ],
        "code_iso_31662": "RU-STA"
    },
    {
        "title": "Хабаровский край",
        "code": 27,
        "gibdd": [
            27,
            127
        ],
        "code_iso_31662": "RU-KHA"
    },
    {
        "title": "Амурская область",
        "code": 28,
        "gibdd": [
            28
        ],
        "code_iso_31662": "RU-AMU"
    },
    {
        "title": "Архангельская область",
        "code": 29,
        "gibdd": [
            29
        ],
        "code_iso_31662": "RU-ARK"
    },
    {
        "title": "Астраханская область",
        "code": 30,
        "gibdd": [
            30,
            130
        ],
        "code_iso_31662": "RU-AST"
    },
    {
        "title": "Белгородская область",
        "code": 31,
        "gibdd": [
            31,
            131
        ],
        "code_iso_31662": "RU-BEL"
    },
    {
        "title": "Брянская область",
        "code": 32,
        "gibdd": [
            32
        ],
        "code_iso_31662": "RU-BRY"
    },
    {
        "title": "Владимирская область",
        "code": 33,
        "gibdd": [
            33,
            133
        ],
        "code_iso_31662": "RU-VLA"
    },
    {
        "title": "Волгоградская область",
        "code": 34,
        "gibdd": [
            34,
            134
        ],
        "code_iso_31662": "RU-VGG"
    },
    {
        "title": "Вологодская область",
        "code": 35,
        "gibdd": [
            35,
            135
        ],
        "code_iso_31662": "RU-VLG"
    },
    {
        "title": "Воронежская область",
        "code": 36,
        "gibdd": [
            36,
            136
        ],
        "code_iso_31662": "RU-VOR"
    },
    {
        "title": "Ивановская область",
        "code": 37,
        "gibdd": [
            37
        ],
        "code_iso_31662": "RU-IVA"
    },
    {
        "title": "Иркутская область",
        "code": 38,
        "gibdd": [
            38,
            138
        ],
        "code_iso_31662": "RU-IRK"
    },
    {
        "title": "Калининградская область",
        "code": 39,
        "gibdd": [
            39,
            91
        ],
        "code_iso_31662": "RU-KGD"
    },
    {
        "title": "Калужская область",
        "code": 40,
        "gibdd": [
            40
        ],
        "code_iso_31662": "RU-KLU"
    },
    {
        "title": "Камчатский край",
        "code": 41,
        "gibdd": [
            41
        ],
        "code_iso_31662": "RU-KAM"
    },
    {
        "title": "Кемеровская область",
        "code": 42,
        "gibdd": [
            42,
            142
        ],
        "code_iso_31662": "RU-KEM"
    },
    {
        "title": "Кировская область",
        "code": 43,
        "gibdd": [
            43
        ],
        "code_iso_31662": "RU-KIR"
    },
    {
        "title": "Костромская область",
        "code": 44,
        "gibdd": [
            44
        ],
        "code_iso_31662": "RU-KOS"
    },
    {
        "title": "Курганская область",
        "code": 45,
        "gibdd": [
            45
        ],
        "code_iso_31662": "RU-KGN"
    },
    {
        "title": "Курская область",
        "code": 46,
        "gibdd": [
            46
        ],
        "code_iso_31662": "RU-KRS"
    },
    {
        "title": "Ленинградская область",
        "code": 47,
        "gibdd": [
            47,
            147
        ],
        "code_iso_31662": "RU-LEN"
    },
    {
        "title": "Липецкая область",
        "code": 48,
        "gibdd": [
            48,
            148
        ],
        "code_iso_31662": "RU-LIP"
    },
    {
        "title": "Магаданская область",
        "code": 49,
        "gibdd": [
            49
        ],
        "code_iso_31662": "RU-MAG"
    },
    {
        "title": "Московская область",
        "code": 50,
        "gibdd": [
            50,
            90,
            150,
            190,
            250,
            550,
            750,
            790
        ],
        "code_iso_31662": "RU-MOS"
    },
    {
        "title": "Мурманская область",
        "code": 51,
        "gibdd": [
            51
        ],
        "code_iso_31662": "RU-MUR"
    },
    {
        "title": "Нижегородская область",
        "code": 52,
        "gibdd": [
            52,
            152,
            252
        ],
        "code_iso_31662": "RU-NIZ"
    },
    {
        "title": "Новгородская область",
        "code": 53,
        "gibdd": [
            53
        ],
        "code_iso_31662": "RU-NGR"
    },
    {
        "title": "Новосибирская область",
        "code": 54,
        "gibdd": [
            54,
            154,
            754
        ],
        "code_iso_31662": "RU-NVS"
    },
    {
        "title": "Омская область",
        "code": 55,
        "gibdd": [
            55,
            155
        ],
        "code_iso_31662": "RU-OMS"
    },
    {
        "title": "Оренбургская область",
        "code": 56,
        "gibdd": [
            56,
            156
        ],
        "code_iso_31662": "RU-ORE"
    },
    {
        "title": "Орловская область",
        "code": 57,
        "gibdd": [
            57
        ],
        "code_iso_31662": "RU-ORL"
    },
    {
        "title": "Пензенская область",
        "code": 58,
        "gibdd": [
            58,
            158
        ],
        "code_iso_31662": "RU-PNZ"
    },
    {
        "title": "Пермский край",
        "code": 59,
        "gibdd": [
            59,
            159
        ],
        "code_iso_31662": "RU-PER"
    },
    {
        "title": "Псковская область",
        "code": 60,
        "gibdd": [
            60
        ],
        "code_iso_31662": "RU-PSK"
    },
    {
